common:
  app:
    url: "%env(APP_URL)%"
    name: "%env(APP_NAME)%"
    version: "%version%"
    logo: "%env(APP_LOGO)%"
    small_logo: "%env(APP_SMALLLOGO)%"
    project_url: https://github.com/SchulIT/servicecenter
    logo_link: 'dashboard'
  locales: "%locales%"
  menu: mainMenu
  disable:
    messenger: true