parameters:
  project_url: https://github.com/schulit/servicecenter

common:
  app:
    url: "%env(APP_URL)%"
    name: "%env(APP_NAME)%"
    version: "%version%"
    project_url: "%project_url%"
    logo: "%env(APP_LOGO)%"
    small_logo: "%env(APP_SMALLLOGO)%"
    logo_link: 'dashboard'
  locales: "%locales%"
  menu: mainMenu
  autoconfig:
    entity_id: '%env(SAML_ENTITY_ID)%'
    app_name: "%env(APP_NAME)%"
    app_icon: 'fas fa-exclamation-triangle'
    saml_cert_file: '%sp_cert_file%'
    role_hierarchy:
      ROLE_SUPER_ADMIN: ~
      ROLE_ADMIN: ~
      ROLE_USER: ~


services:
  SchulIT\CommonBundle\Monolog\DatabaseHandler:
    autoconfigure: true
    autowire: true
    arguments:
      $connection: '@doctrine.dbal.logger_connection'
