framework:
    messenger:
        # reset services after consuming messages
        reset_on_message: true

        transports:
            async: "%env(MESSENGER_TRANSPORT_DSN)%"

        routing:
            'Symfony\Component\Mailer\Messenger\SendEmailMessage': async
