# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle/tree/master/Resources/doc/index.md
oneup_flysystem:
    adapters:
        uploads:
            local:
                location: "%kernel.project_dir%/public/uploads"

    filesystems:
        uploads:
            adapter: uploads
            mount: uploads